const fs = require('fs');
const path = require('path');

const filePath = path.resolve('presentacion.html');
let html = fs.readFileSync(filePath, 'utf8');

// -----------------------------------------------------------------------
// 1. HIDE DOTS — add CSS class to the pres-dots container
// -----------------------------------------------------------------------
html = html.replace(
  '<!-- DOT NAVIGATION (generated by JS) -->\r\n    <div class="pres-dots"></div>',
  '<!-- DOT NAVIGATION (generated by JS) -->\r\n    <div class="pres-dots" style="display:none"></div>'
);

// -----------------------------------------------------------------------
// 2. EXTRACT every slide block between its <!-- === --> comment markers
//    Strategy: split on the opening comment pattern, reassemble in new order
// -----------------------------------------------------------------------
const COMMENT_RE = /(\s*)(<!--\s*={5,}\s*(SLIDE|CAP)\s[\s\S]+?={5,}\s*-->\s*<div class="slide[^>]*>[\s\S]*?<\/div>\s*(?:\r?\n))/g;

// Collect all blocks with their keys
const blocks = {};
let m;
while ((m = COMMENT_RE.exec(html)) !== null) {
  const full = m[2];
  if (full.includes('CAP 01')) blocks.CAP1 = full;
  else if (full.includes('CAP 02')) blocks.CAP2 = full;
  else if (full.includes('CAP 03')) blocks.CAP3 = full;
  else if (full.includes('CAP 04')) blocks.CAP4 = full;
  else if (full.includes('CAP 05')) blocks.CAP5 = full;
  else if (full.includes('SLIDE 01')) blocks.S01 = full;
  else if (full.includes('SLIDE 02')) blocks.S02 = full;
  else if (full.includes('SLIDE 03')) blocks.S03 = full;
  else if (full.includes('SLIDE 04')) blocks.S04 = full;
  else if (full.includes('SLIDE 05')) blocks.S05 = full;
  else if (full.includes('SLIDE 06')) blocks.S06 = full;
  else if (full.includes('SLIDE 07 (NUEVO)')) blocks.S07NUEVO = full;
  else if (full.includes('SLIDE 08 (NUEVO)')) blocks.S08NUEVO = full;
  else if (full.includes('SLIDE 07')) blocks.S07 = full;
  else if (full.includes('SLIDE 08')) blocks.S08 = full;
  else if (full.includes('SLIDE 09')) blocks.S09 = full;
  else if (full.includes('SLIDE 12 (NUEVO)')) blocks.S12NUEVO = full;
  else if (full.includes('SLIDE 10')) blocks.S10 = full;
  else if (full.includes('SLIDE 11')) blocks.S11 = full;
  else if (full.includes('SLIDE 12')) blocks.S12 = full;
  else if (full.includes('SLIDE 13')) blocks.S13 = full;
}

console.log('Blocks captured:', Object.keys(blocks).join(', '));
fs.writeFileSync('blocks_debug.json', JSON.stringify(Object.keys(blocks)), 'utf8');
